version: "3.8"

services:
  web:
    image: saiif/todo-app:latest
    ports:
      - "80:5000"
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    networks:
      - todo-net

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mytododb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - todo-net

volumes:
  db-data:

networks:
  todo-net:
