services:
  web:
    image: saiif/todo-app:latest
    ports:
      - "80:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: todo
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    networks:
      - todo-net

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todo
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.role == worker]
    networks:
      - todo-net
