version: '3.8'

services:
  web:
    image: saiif/todo-app:latest
    ports:
      - "80:5000"  # ← Map container's port 5000 to host's port 80
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: todo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    networks:
      - todo-net

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todo
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - todo-net

volumes:
  db-data:

networks:
  todo-net:
