version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mytododb
    volumes:
      - db_data:/var/lib/mysql
      - ./todo-db.sql:/docker-entrypoint-initdb.d/todo-db.sql

volumes:
  db_data:

